const dummydata = [
  {
    id: 1,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI settings.",
    price: 15.99,
    category: "Electronics",
    stock: 120,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    name: "Gaming Keyboard",
    description: "Mechanical gaming keyboard with RGB backlighting.",
    price: 49.99,
    category: "Electronics",
    stock: 75,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    name: "Running Shoes",
    description: "Lightweight running shoes with breathable mesh fabric.",
    price: 60.0,
    category: "Footwear",
    stock: 200,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    name: "Backpack",
    description: "Durable backpack with multiple compartments for travel.",
    price: 30.5,
    category: "Accessories",
    stock: 150,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    name: "Smartwatch",
    description: "Fitness smartwatch with heart rate monitoring and GPS.",
    price: 120.99,
    category: "Electronics",
    stock: 50,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    name: "Coffee Mug",
    description: "Ceramic coffee mug with a capacity of 350ml.",
    price: 10.0,
    category: "Kitchenware",
    stock: 300,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    name: "Yoga Mat",
    description: "Non-slip yoga mat with a thickness of 6mm.",
    price: 25.0,
    category: "Fitness",
    stock: 100,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with 10 hours of battery life.",
    price: 35.99,
    category: "Electronics",
    stock: 60,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    name: "Notebook",
    description: "Hardcover notebook with 200 lined pages.",
    price: 8.99,
    category: "Stationery",
    stock: 500,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    name: "Desk Lamp",
    description: "Adjustable LED desk lamp with three brightness settings.",
    price: 22.5,
    category: "Home Office",
    stock: 80,
    imageUrl: "https://via.placeholder.com/150",
  },
];

export default dummydata;
